### ISSUE TITLE
Cannot assign to a struct member

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#120]
**Describe the bug**
Instead of incrementing a struct member, rcc crashes at compile time.

**Code**

```c
struct dict {
    int num_items;
} *my_dict;

int main() {
    ++my_dict->num_items;
}
thread 'main' panicked at 'not yet implemented: what's an lval but not a pointer or id?', src/parse/expr.rs:1156:18
```

<details><summary>AST</summary>

Please paste the output of `cargo run -- --debug-ast` here.

```
auto struct dict *my_dict;
thread 'main' panicked at 'not yet implemented: what's an lval but not a pointer or id?', src/parse/expr.rs:1156:18
```

</details>

<details><summary>Backtrace</summary>

```
  13: rcc::parse::expr::<impl rcc::data::Expr>::is_modifiable_lval
             at src/parse/expr.rs:1156
  14: rcc::parse::expr::<impl rcc::data::Expr>::increment_op
             at src/parse/expr.rs:1360
  15: rcc::parse::expr::<impl rcc::parse::Parser<I>>::unary_expr
             at src/parse/expr.rs:539
  16: rcc::parse::expr::<impl rcc::parse::Parser<I>>::cast_expr
             at src/parse/expr.rs:522
```

</details>

**Comment by jyn514** [comment]
Pretty-printed expr: thread 'main' panicked at `(*(my_dict)).num_items`. The parser doesn't know how to handle struct members.

**Comment by jyn514** [comment]
Related #103

**Comment by jyn514** [comment]
lol now this segfaults instead of giving an error

```c
$ cargo run
struct dict {
    int num_items;
} *my_dict;

int main() {
        my_dict->num_items = 1;
}
$ ./a.out 
Segmentation fault
```

**Comment by jyn514** [comment]
Possibly related: https://github.com/jyn514/rcc/issues/103

**Comment by jyn514** [comment]
clang compiles this as

```
        xorl    %eax, %eax
        movq    my_dict, %rcx
        movl    $1, (%rcx)
```

gcc is essentially the same. This also compiles to the same code for structs in local scope which surprises me.

**Comment by jyn514** [comment]
```
struct dict {
    int num_items;                                                                           
} my_dict;
int main() {
        my_dict.num_items = 1;
}
```
compiles as
```
        xorl    %eax, %eax
        movl    $1, my_dict
```

**Comment by jyn514** [comment]
We actually get that second case right, it's just struct pointers that are wrong.

**Comment by jyn514** [comment]
gaaah this was just a bad test case, it works fine with

```c
struct dict {
    int num_items;
} *my_dict;

int main() {
        struct dict d;
        my_dict = &d;
        return my_dict->num_items = 1;
}
```
