### ISSUE TITLE
Cannot pass structs as rvals

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#140]
```c
struct s {
        int i, j; 
};
int f(struct s my_s) {
        return my_s.i;
}
thread 'main' panicked at 'INVALID encountered', /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.51.0/src/ir/types.rs:322:28
```

Same bug for returning structs:

```c
struct s {
        int i, j; 
} s = {1, 2};
struct s f() {
        return s;
}
thread 'main' panicked at 'INVALID encountered', /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.51.0/src/ir/types.rs:322:28
```

**Comment by jyn514** [comment]
The problem is that structs are not scalar. Maybe this needs to pass a hidden output parameter for 2? And a pointer instead of an rval for 1? Need to look how clang does it.

**Comment by jyn514** [comment]
Yeah it looks like clang returns a pointer, not the actual struct for 2:

```assembly
f:                                      # @f
# %bb.0:
        pushq   %rbp
        movq    %rsp, %rbp
        movq    s, %rax
        movq    %rax, -8(%rbp)
        movq    -8(%rbp), %rax
        popq    %rbp
        retq
.Lfunc_end0:
        .size   f, .Lfunc_end0-f
                                        # -- End function
        .type   s,@object               # @s
        .data
        .globl  s
        .p2align        2
s:
        .long   1                       # 0x1
        .long   2                       # 0x2
        .size   s, 8
```

and for 1 it looks like it returns the same address it was passed? not sure I understand this code, unless clang is passing arguments in registers:

```assembly
f:                                      # @f
# %bb.0:
        pushq   %rbp
        movq    %rsp, %rbp
        movq    %rdi, -8(%rbp)
        movl    -8(%rbp), %eax
        popq    %rbp
        retq
```

**Comment by jyn514** [comment]
To fix this, the backend needs to rewrite
```c
struct s {
        int i, j; 
} s = {1, 2};
struct s f() {
        return s;
}
```
to
```c
void f(struct s *ptr) {
    ptr->i = s->i;
    ptr->j = s->j;
}
```
