### ISSUE TITLE
[ICE] crash on array initializer with misleading number of braces

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#209]
**Expected behavior**
`h` is initialized to a 1x3 array of char.

**Actual Behavior**
rcc panics during initialization.

**Code**

```c
    char h[] [3] = {1, 2, 3};
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `3`,
 right: `8`: destination and source slices have different lengths', src/libcore/slice/mod.rs:2217:9
```

<details><summary>Backtrace</summary>

```
  14: core::slice::<impl [T]>::copy_from_slice
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/macros.rs:52
  15: rcc::ir::static_init::<impl rcc::ir::Compiler>::init_expr
             at src/ir/static_init.rs:163
  16: rcc::ir::static_init::<impl rcc::ir::Compiler>::init_symbol
             at src/ir/static_init.rs:254
  17: rcc::ir::static_init::<impl rcc::ir::Compiler>::init_array
             at src/ir/static_init.rs:285
  18: rcc::ir::static_init::<impl rcc::ir::Compiler>::init_symbol
             at src/ir/static_init.rs:213
  19: rcc::ir::static_init::<impl rcc::ir::Compiler>::store_static
             at src/ir/static_init.rs:86
  20: rcc::ir::compile
             at src/ir/mod.rs:89
  21: rcc::compile
             at src/lib.rs:98
  22: rcc::real_main
             at src/main.rs:99
  23: rcc::main
             at src/main.rs:164
```

</details>

Thanks to @byter09 for the fuzzing :)

**Comment by jyn514** [comment]
Using `char h[][3] = {{1, 2, 3}};` works, I think this is a problem in `src/parse/decl.rs` actually.

**Comment by jyn514** [comment]
Everything relevant the standard has to say:

> 16 Otherwise, the initializer for an object that has aggregate or union type shall be a brace- enclosed list of initializers for the elements or named members.

> 17 Each brace-enclosed initializer list has an associated current object. When no designations are present, subobjects of the current object are initialized in order according to the type of the current object: array elements in increasing subscript order, structure members in declaration order, and the first named member of a union.148) In contrast, a designation causes the following initializer to begin initialization of the subobject described by the designator. Initialization then continues forward in order, beginning with the next subobject after that described by the designator.149)

> 18 Each designator list begins its description with the current object associated with the closest surrounding brace pair. Each item in the designator list (in order) specifies a particular member of its current object and changes the current object for the next designator (if any) to be that member.150) The current object that results at the end of the designator list is the subobject to be initialized by the following initializer.

> 19 The initialization shall occur in initializer list order, each initializer provided for a particular subobject overriding any previously listed initializer for the same subobject;151) all subobjects that are not initialized explicitly shall be initialized implicitly the same as objects that have static storage duration.

> 20 If the aggregate or union contains elements or members that are aggregates or unions, these rules apply recursively to the subaggregates or contained unions. If the initializer of a subaggregate or contained union begins with a left brace, the initializers enclosed by that brace and its matching right brace initialize the elements or members of the subaggregate or the contained union. Otherwise, only enough initializers from the list are taken to account for the elements or members of the subaggregate or the first member of the contained union; any remaining initializers are left to initialize the next element or member of the aggregate of which the current subaggregate or contained union is a part.

> 22 If an array of unknown size is initialized, its size is determined by the largest indexed element with an explicit initializer. The array type is completed at the end of its initializer list. 

There's a lot of things we're doing wrong here, I'm not going to fix this tonight.

**Comment by jyn514** [comment]
Ok, I think I found the problem: we call `type_at()` in `initializer()` for initializer lists, but don't check whether the type is scalar or aggregate.

**Comment by jyn514** [comment]
I have a fix for the immediate ICE, but I'm still not sure why `{1, 2, 3}` should initialize the inner array instead of being an error.

**Comment by jyn514** [comment]
So it appears this can nest arbitrarily deep.

```c
char h[][1][1][1][3] = {1,2,3};
<stdin>:1:25: warning: suggest braces around initialization of subobject
      [-Wmissing-braces]
char h[][1][1][1][3] = {1,2,3};
                        ^~~~~
                        {    }
<stdin>:1:25: warning: suggest braces around initialization of subobject
<stdin>:1:25: warning: suggest braces around initialization of subobject
<stdin>:1:25: warning: suggest braces around initialization of subobject
```
