### ISSUE TITLE
struct/union/enum

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#21]
- [x] struct
- [x] union
- [x] enum

**Comment by jyn514** [comment]
Error is different since https://github.com/jyn514/rcc/commit/ae2c94e904c86286269a6d2747d2da641c105c54:

```c
struct s;
thread 'main' panicked at 'not yet implemented: structs, unions, and enums', src/parse/decl.rs:371:9
```

**Comment by jyn514** [comment]
Enums are done since https://github.com/jyn514/rcc/commit/ddc165ccd2f792be5cdeae28b5969d6b131f4f1a!

**Comment by jyn514** [comment]
Struct and union declarations are done. Need to implement expressions and codegen.

```
struct s { int i; } s;
int main() {
        return s.i;
}
thread 'main' panicked at 'not yet implemented: struct and union members are very much not implemented', src/parse/expr.rs:706:33
```

**Comment by jyn514** [comment]
Possible ways to implement this:

Have a cache in `ir::LLVMCompiler` that stores offsets into structs. For unions, the offset is always zero. The size of a struct is the greatest offset + sizeof(member at that offset). Accessing a struct member is fetching *(s + offset).

Ways to calculate the offset: For now, just do sizeof(member) + (8-sizeof(member))%8.
In the future, sort members from largest size to smallest, excluding arrays. Put chars, shorts in spare bytes.

**Comment by jyn514** [comment]
Done in https://github.com/jyn514/rcc/commit/01f53f224c43a9ba9a66be3d90935dd8cab1f1ba!!!
