### ISSUE TITLE
[ICE] crash on void function call in negation

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#212]
**Expected behavior**
RCC should give a semantic error, like clang:
```c
<stdin>:3:17: error: invalid argument type 'void' to unary expression
        switch(1) f(), !f();
                       ^~~~
```

**Actual Behavior**
RCC crashes.

**Code**

```c
void f();
int main() {
	switch(1) f(), !f();
}
thread 'main' panicked at 'internal error: entered unreachable code: all scalars should be float, int, or bool', src/ir/expr.rs:449:18
```

<details><summary>Backtrace</summary>

```
  13: rcc::ir::expr::<impl rcc::ir::Compiler>::logical_not
  14: rcc::ir::expr::<impl rcc::ir::Compiler>::compile_expr
  15: rcc::ir::expr::<impl rcc::ir::Compiler>::compile_expr
  16: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_stmt
  17: rcc::ir::stmt::<impl rcc::ir::Compiler>::switch
  18: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_stmt
  19: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_all
  20: rcc::ir::Compiler::compile_func
  21: rcc::ir::compile
  22: rcc::compile
  23: rcc::real_main
  24: rcc::main
```

</details>

Thanks to @byter09 for the fuzzing.

**Comment by jyn514** [comment]
Related: this causes a double-panic.

```c
void f();
int main() {
    return (int)f(); 
}
thread 'main' panicked at 'INVALID encountered', /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.56.0/src/ir/types.rs:322:28
thread panicked while panicking. aborting.
```
