### ISSUE TITLE
[ICE] crash on duplicate case labels

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#221]
**Expected behavior**
RCC should give a semantic error.

**Actual Behavior**
RCC crashes during codegen.

**Code**

```c
int main() {
	switch(1) {
		case 1: case 1: return 1;
	}
}
thread 'main' panicked at 'Tried to set the same entry 1 twice', /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-frontend-0.56.0/src/switch.rs:58:9
```

<details><summary>Backtrace</summary>

```
  13: cranelift_frontend::switch::Switch::set_entry
  14: rcc::ir::stmt::<impl rcc::ir::Compiler>::case
  15: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_stmt
  16: rcc::ir::stmt::<impl rcc::ir::Compiler>::case
  17: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_stmt
  18: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_all
  19: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_stmt
  20: rcc::ir::stmt::<impl rcc::ir::Compiler>::switch
  21: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_stmt
  22: rcc::ir::stmt::<impl rcc::ir::Compiler>::compile_all
  23: rcc::ir::Compiler::compile_func
  24: rcc::ir::compile
  25: rcc::compile
  26: rcc::real_main
  27: rcc::main
```

</details>

Waiting on Cranelift to publish https://github.com/bytecodealliance/cranelift/pull/1358.

**Comment by jyn514** [comment]
Hmm, I thought I fixed this in https://github.com/jyn514/rcc/tree/duplicate-case, but it still crashes on this input:

```c
int main() {
    switch(1)
      case 2: case 3: case 3:
        return 0;
}
thread 'main' panicked at 'Tried to set the same entry 3 twice', /home/joshua/.local/lib/cargo/git/checkouts/cranelift-e5a6a40e8f744a9d/765d3d8/cranelift-frontend/src/switch.rs:58:9
```

**Comment by jyn514** [comment]
Whoop, I only put it in one arm of the else!
