### ISSUE TITLE
[ICE] Divide by zero error while calculating alignment

### ISSUE THREAD

**Issue by pythondude325** [jyn514/rcc#236]
**Expected behavior**
I don't even know, some kind of error

**Actual Behavior**
```
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', src/arch/mod.rs:138:19
```

**Code**
```c
struct s {
    struct int i;
} S;

int main() {
    &S + 0;
}
```

Note: I think the `int` keyword on line 2 can be any keyword. This may indicate that the error occurs while parsing the type.

<details><summary>Backtrace</summary>

```
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', src/arch/mod.rs:138:19
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::panicking::panic
             at src/libcore/panicking.rs:70
  15: rcc::arch::<impl rcc::data::types::Type>::next_offset
  16: rcc::arch::struct_size::{{closure}}
  17: core::iter::traits::iterator::Iterator::try_fold
  18: rcc::arch::struct_size
  19: rcc::arch::<impl rcc::data::types::Type>::sizeof
  20: rcc::parse::expr::<impl rcc::data::Expr>::pointer_arithmetic
  21: rcc::parse::expr::<impl rcc::parse::Parser<I>>::additive_expr::{{closure}}
  22: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  23: rcc::parse::expr::<impl rcc::parse::Parser<I>>::additive_expr
  24: core::ops::function::Fn::call
  25: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  26: rcc::parse::expr::<impl rcc::parse::Parser<I>>::integral_left_associative_binary_op
  27: rcc::parse::expr::<impl rcc::parse::Parser<I>>::shift_expr
  28: core::ops::function::Fn::call
  29: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  30: rcc::parse::expr::<impl rcc::parse::Parser<I>>::relational_expr
  31: core::ops::function::Fn::call
  32: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  33: rcc::parse::expr::<impl rcc::parse::Parser<I>>::equality_expr
  34: core::ops::function::Fn::call
  35: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  36: rcc::parse::expr::<impl rcc::parse::Parser<I>>::integral_left_associative_binary_op
  37: rcc::parse::expr::<impl rcc::parse::Parser<I>>::and_expr
  38: core::ops::function::Fn::call
  39: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  40: rcc::parse::expr::<impl rcc::parse::Parser<I>>::integral_left_associative_binary_op
  41: rcc::parse::expr::<impl rcc::parse::Parser<I>>::exclusive_or_expr
  42: core::ops::function::Fn::call
  43: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  44: rcc::parse::expr::<impl rcc::parse::Parser<I>>::integral_left_associative_binary_op
  45: rcc::parse::expr::<impl rcc::parse::Parser<I>>::inclusive_or_expr
  46: core::ops::function::Fn::call
  47: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  48: rcc::parse::expr::<impl rcc::parse::Parser<I>>::scalar_left_associative_binary_op
  49: rcc::parse::expr::<impl rcc::parse::Parser<I>>::logical_and_expr
  50: core::ops::function::Fn::call
  51: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  52: rcc::parse::expr::<impl rcc::parse::Parser<I>>::scalar_left_associative_binary_op
  53: rcc::parse::expr::<impl rcc::parse::Parser<I>>::logical_or_expr
  54: rcc::parse::expr::<impl rcc::parse::Parser<I>>::conditional_expr
  55: rcc::parse::expr::<impl rcc::parse::Parser<I>>::assignment_expr
  56: core::ops::function::Fn::call
  57: rcc::parse::expr::<impl rcc::parse::Parser<I>>::left_associative_binary_op
  58: rcc::parse::expr::<impl rcc::parse::Parser<I>>::expr
  59: rcc::parse::stmt::<impl rcc::parse::Parser<I>>::expression_statement
  60: rcc::parse::stmt::<impl rcc::parse::Parser<I>>::statement
  61: rcc::parse::stmt::<impl rcc::parse::Parser<I>>::compound_statement
  62: rcc::parse::decl::<impl rcc::parse::Parser<I>>::function_body
  63: rcc::parse::decl::<impl rcc::parse::Parser<I>>::declaration
  64: <rcc::parse::Parser<I> as core::iter::traits::iterator::Iterator>::next::{{closure}}
  65: core::option::Option<T>::or_else
  66: <rcc::parse::Parser<I> as core::iter::traits::iterator::Iterator>::next
  67: <&mut I as core::iter::traits::iterator::Iterator>::next
  68: rcc::parse::Parser<I>::collect_results
  69: rcc::compile
  70: rcc::real_main
  71: rcc::main
  72: std::rt::lang_start::{{closure}}
  73: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  74: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  75: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  76: std::panicking::try
             at src/libstd/panicking.rs:265
  77: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  78: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  79: std::rt::lang_start
  80: main
  81: __libc_start_main
  82: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

**Comment by jyn514** [comment]
This is fixed on master.
