### ISSUE TITLE
if with return and no else does not compile

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#29]
```c
int main() {
        if (1) { 
                return 1;
        }
}
thread 'main' panicked at 'should not have a compile error: VerifierErrors([VerifierError { location: inst1, message: "invalid ebb reference ebb2" }])', src/libcore/result.rs:999:5
```

Compare an explicit return, which works fine:

```
int main() {
        if (1) { 
                return 1;
        }
        return 0;
}
```

<details><summary>asm</summary>

```
function u0:0() -> i32 system_v {
ebb0:
    v0 = iconst.i32 1
    brz v0, ebb2
    jump ebb1

ebb1:
    v1 = iconst.i32 1
    return v1
}
```

</details>

<details><summary>backtrace</summary>

```
thread 'main' panicked at 'should not have a compile error: VerifierErrors([VerifierError { location: inst1, message: "invalid ebb reference ebb2" }])', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::expect
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:827
  12: compiler::ir::LLVMCompiler::compile_func
             at src/ir.rs:248
  13: compiler::ir::compile
             at src/ir.rs:77
  14: compiler::compile
             at src/lib.rs:72
  15: compiler::real_main
             at src/main.rs:63
  16: compiler::main
             at src/main.rs:109
  17: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  21: std::panicking::try
             at src/libstd/panicking.rs:275
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  24: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  25: main
  26: __libc_start_main
  27: _start
```

</details>

<details><summary>AST</summary>

```
FunctionBody(
                        [
                            Locatable {
                                data: If(
                                    Expr {
                                        expr: Literal(
                                            Int(
                                                1,
                                            ),
                                        ),
                                        ctype: Int(
                                            true,
                                        ),
                                        constexpr: true,
                                        lval: false,
                                        location: Location {
                                            line: 2,
                                            column: 14,
                                            file: "<stdin>",
                                        },
                                    },
                                    Locatable {
                                        data: Compound(
                                            [
                                                Locatable {
                                                    data: Return(
... snip ...
```

</details>

**Comment by jyn514** [comment]
AST is not inserting a `return` when it hasn't been seen, this would pop up anywhere there's a condition where not all of the branches has a return (compare `if (1) { return 1; } else {}`).

It would be better to insert a return in `ir`, where we're already looking at EBBs and know if there's been a return or not.
