### ISSUE TITLE
Forward declarations are still broken

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#44]
```c
struct s my_s;
struct s { int i; };
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(1)`,
 right: `Some(0)`', /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/faerie-0.11.0/src/artifact/decl.rs:453:5
```

Need to update all types in scope, not just typedefs :( this won't be hard but it'll be really slow

**Comment by jyn514** [comment]
Add an API to Parser that shows the current types in scope? The backend only needs it for top level declarations so scoping shouldn't be an issue. Not sure if this will play well with lifetimes.

**Comment by jyn514** [comment]
Related:

```c
struct s {
        int i;
        struct s s;
};
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', src/backend/mod.rs:135:16
```

**Comment by jyn514** [comment]
That last bit is fixed on master.

```c
struct s {
        int i;
        struct s s;
};
<stdin>:3:19: error: cannot use type 'struct s' before it has been defined
1 error generated
```

**Comment by jyn514** [comment]
Updated error for original code:

```c
struct s my_s;
struct s { int i; };
int main() {
  return my_s.i;
}
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
```

**Comment by jyn514** [comment]
Fixed in https://github.com/jyn514/rcc/pull/130
