### ISSUE TITLE
Variables in loop conditions are not dereferenced

### ISSUE THREAD

**Issue by xTachyon** [jyn514/rcc#70]
This code:
```int puts(const char *s);
int putchar(char);

void itoa(int value, char* str) {
    if (value == 0) {
        str[0] = '0';
        str[0] = 0;
    } else {
        while (value) {
            *str = value % 10 + '0';
            value /= 10;
        }
        *str = 0;
    }
}

void ff() {
    int v = 5 & 2 == 1;
    char buffer[10];
    itoa(v, buffer);
}

int main() {
    void (*function)() = ff;
    function();
}
```

panicks with:

```    Finished dev [unoptimized] target(s) in 0.02s
     Running `target/debug/rcc test.c --debug-asm`
function u0:0(i32, i64) system_v {
    ss0 = explicit_slot 4
    ss1 = explicit_slot 8

ebb0(v0: i32, v1: i64):
    v2 = stack_addr.i64 ss0
    store v0, v2
    v3 = stack_addr.i64 ss1
    store v1, v3
    v4 = stack_addr.i64 ss0
    v5 = load.i32 v4
    v6 = sextend.i64 v5
    v7 = iconst.i64 0
    v8 = icmp eq v6, v7
    brz v8, ebb3
    jump ebb1

ebb1:
    v9 = stack_addr.i64 ss1
    v10 = load.i64 v9
    v11 = iconst.i64 1
    v12 = iconst.i64 0
    v13 = imul v11, v12
    v14 = iadd v10, v13
    v15 = iconst.i8 48
    store v15, v14
    v16 = stack_addr.i64 ss1
    v17 = load.i64 v16
    v18 = iconst.i64 1
    v19 = iconst.i64 0
    v20 = imul v18, v19
    v21 = iadd v17, v20
    v22 = iconst.i8 0
    store v22, v21
    jump ebb2

ebb3:
    jump ebb4

ebb4:
    v23 = stack_addr.i64 ss0
    v24 = iconst.i32 0
    v25 = icmp ne v23, v24
    brz v25, ebb5
    v26 = stack_addr.i64 ss1
    v27 = load.i64 v26
    v28 = stack_addr.i64 ss0
    v29 = load.i32 v28
    v30 = sextend.i64 v29
    v31 = iconst.i64 10
    v32 = srem v30, v31
    v33 = iconst.i8 48
    v34 = sextend.i64 v33
    v35 = iadd v32, v34
    v36 = ireduce.i8 v35
    store v36, v27
    v37 = stack_addr.i64 ss0
    v38 = iconst.i32 10
    v39 = load.i32 v37
    v40 = sdiv v39, v38
    store v40, v37
    jump ebb4

ebb5:
    v41 = stack_addr.i64 ss1
    v42 = load.i64 v41
    v43 = iconst.i8 0
    store v43, v42
    jump ebb2

ebb2:
    return
}

thread 'main' panicked at 'should not have a compile error: VerifierErrors([VerifierError { location: inst31, message: "arg 1 (v24) has type i32, expected i64" }])', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55be95381514 - backtrace::backtrace::libunwind::trace::h7eb4b43b611b7867
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55be95381514 - backtrace::backtrace::trace_unsynchronized::hd915225b960621fe
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55be95381514 - std::sys_common::backtrace::_print_fmt::h03e09238238aa7ea
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55be95381514 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd2bc77662b898564
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55be953a421c - core::fmt::write::h8ebd3dea7d60af99
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55be9537f417 - std::io::Write::write_fmt::hcc91da7d626d8d3c
                               at src/libstd/io/mod.rs:1412
   6:     0x55be95383935 - std::sys_common::backtrace::_print::h71d790ff242dd25b
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55be95383935 - std::sys_common::backtrace::print::h0598a41f9f73dcfd
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55be95383935 - std::panicking::default_hook::{{closure}}::h402ca543df8941ce
                               at src/libstd/panicking.rs:200
   9:     0x55be95383626 - std::panicking::default_hook::h654c705cfbcaa6d8
                               at src/libstd/panicking.rs:214
  10:     0x55be95383fd5 - std::panicking::rust_panic_with_hook::h56efa3c9265fc6c3
                               at src/libstd/panicking.rs:477
  11:     0x55be95383b72 - std::panicking::continue_panic_fmt::h21f1f952a36d712d
                               at src/libstd/panicking.rs:384
  12:     0x55be95383a66 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
  13:     0x55be953a0f8a - core::panicking::panic_fmt::hb830357db65719c4
                               at src/libcore/panicking.rs:85
  14:     0x55be953a1087 - core::result::unwrap_failed::h5f28b5cc4e4e1e10
                               at src/libcore/result.rs:1165
  15:     0x55be94e7b0ca - core::result::Result<T,E>::expect::hc037640d873b054b
  16:     0x55be94eb2780 - rcc::ir::Compiler::compile_func::h1dd6e5f26253a090
  17:     0x55be94eadcfc - rcc::ir::compile::hb87f814586d1d061
  18:     0x55be94df61e3 - rcc::compile::h76ca3fe1ac5ee96a
  19:     0x55be94d778ea - rcc::real_main::h78dff5372371403b
  20:     0x55be94d787fe - rcc::main::hbce502b21dd81625
  21:     0x55be94d7b943 - std::rt::lang_start::{{closure}}::h9b6983430a4f3e85
  22:     0x55be95383a03 - std::rt::lang_start_internal::{{closure}}::hf45371a278d88d9f
                               at src/libstd/rt.rs:49
  23:     0x55be95383a03 - std::panicking::try::do_call::h0a6c8fe2c9f70474
                               at src/libstd/panicking.rs:296
  24:     0x55be9538a1da - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  25:     0x55be953844cd - std::panicking::try::h8f403e10a442d986
                               at src/libstd/panicking.rs:275
  26:     0x55be953844cd - std::panic::catch_unwind::hd1e18a7065c37a62
                               at src/libstd/panic.rs:394
  27:     0x55be953844cd - std::rt::lang_start_internal::hce3187f9b457de0f
                               at src/libstd/rt.rs:48
  28:     0x55be94d7b928 - std::rt::lang_start::hacecdad9516aef62
  29:     0x55be94d79cab - main
  30:     0x7f8118983ee3 - __libc_start_main
  31:     0x55be94d7518e - _start
  32:                0x0 - <unknown>
```

My guess is the else branch of the itoa function, but who knows.

**Comment by jyn514** [comment]
This is the while condition of the loop, I have a smaller reproduction:

```c
$ target/debug/rcc --debug-asm
int main(int argc, char**argv) {                                                             
        while (argc);                                                                        
}
function u0:0(i32, i64) -> i32 system_v {
    ss0 = explicit_slot 4
    ss1 = explicit_slot 8

ebb0(v0: i32, v1: i64):
    v2 = stack_addr.i64 ss0
    store v0, v2
    v3 = stack_addr.i64 ss1
    store v1, v3
    jump ebb1

ebb1:
    v4 = stack_addr.i64 ss0
    v5 = iconst.i32 0
    v6 = icmp ne v4, v5
    brz v6, ebb2
    jump ebb1

ebb2:
    v7 = iconst.i32 0
    return v7
}

thread 'main' panicked at 'should not have a compile error: VerifierErrors([VerifierError { location: inst7, message: "arg 1 (v5) has type i32, expected i64" }])', src/libcore/result.rs:1084:5
```

Probably an issue with `Expr::truthy`.
