### ISSUE TITLE
Struct assigment panics

### ISSUE THREAD

**Issue by xTachyon** [jyn514/rcc#71]
```
struct S {
    int x;
};

int main() {
    struct S s;
    struct S ss;
    s = ss;
}
```

error:
```
    Finished dev [unoptimized] target(s) in 0.02s
     Running `target/debug/rcc test.c --debug-asm`
thread 'main' panicked at 'Polymorphic instruction must produce a result', /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.44.0/src/write.rs:385:5
stack backtrace:
   0:     0x558485bf9514 - backtrace::backtrace::libunwind::trace::h7eb4b43b611b7867
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x558485bf9514 - backtrace::backtrace::trace_unsynchronized::hd915225b960621fe
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x558485bf9514 - std::sys_common::backtrace::_print_fmt::h03e09238238aa7ea
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x558485bf9514 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd2bc77662b898564
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x558485c1c21c - core::fmt::write::h8ebd3dea7d60af99
                               at src/libcore/fmt/mod.rs:1030
   5:     0x558485bf7417 - std::io::Write::write_fmt::hcc91da7d626d8d3c
                               at src/libstd/io/mod.rs:1412
   6:     0x558485bfb935 - std::sys_common::backtrace::_print::h71d790ff242dd25b
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x558485bfb935 - std::sys_common::backtrace::print::h0598a41f9f73dcfd
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x558485bfb935 - std::panicking::default_hook::{{closure}}::h402ca543df8941ce
                               at src/libstd/panicking.rs:200
   9:     0x558485bfb626 - std::panicking::default_hook::h654c705cfbcaa6d8
                               at src/libstd/panicking.rs:214
  10:     0x558485bfbfd5 - std::panicking::rust_panic_with_hook::h56efa3c9265fc6c3
                               at src/libstd/panicking.rs:477
  11:     0x558485bab3a5 - std::panicking::begin_panic::h512bc051e37174c1
  12:     0x558485a6f199 - cranelift_codegen::write::type_suffix::h41efdbbdbdd90cfd
  13:     0x558485a70821 - cranelift_codegen::write::write_instruction::h9e1f3a31b8b691df
  14:     0x558485a6c58b - <cranelift_codegen::write::PlainWriter as cranelift_codegen::write::FuncWriter>::write_instruction::h3bb10fd31a3a7ae6
  15:     0x558485a6eec7 - cranelift_codegen::write::decorate_ebb::hc3cf838c67d5a6ed
  16:     0x558485a6cd41 - cranelift_codegen::write::decorate_function::h4b52e38870d67afb
  17:     0x558485a6c633 - cranelift_codegen::write::write_function::hd2f3cc7ed0200f52
  18:     0x55848572a600 - rcc::ir::Compiler::compile_func::h1dd6e5f26253a090
  19:     0x558485725cfc - rcc::ir::compile::hb87f814586d1d061
  20:     0x55848566e1e3 - rcc::compile::h76ca3fe1ac5ee96a
  21:     0x5584855ef8ea - rcc::real_main::h78dff5372371403b
  22:     0x5584855f07fe - rcc::main::hbce502b21dd81625
  23:     0x5584855f3943 - std::rt::lang_start::{{closure}}::h9b6983430a4f3e85
  24:     0x558485bfba03 - std::rt::lang_start_internal::{{closure}}::hf45371a278d88d9f
                               at src/libstd/rt.rs:49
  25:     0x558485bfba03 - std::panicking::try::do_call::h0a6c8fe2c9f70474
                               at src/libstd/panicking.rs:296
  26:     0x558485c021da - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  27:     0x558485bfc4cd - std::panicking::try::h8f403e10a442d986
                               at src/libstd/panicking.rs:275
  28:     0x558485bfc4cd - std::panic::catch_unwind::hd1e18a7065c37a62
                               at src/libstd/panic.rs:394
  29:     0x558485bfc4cd - std::rt::lang_start_internal::hce3187f9b457de0f
                               at src/libstd/rt.rs:48
  30:     0x5584855f3928 - std::rt::lang_start::hacecdad9516aef62
  31:     0x5584855f1cab - main
  32:     0x7f9f389c3ee3 - __libc_start_main
  33:     0x5584855ed18e - _start
  34:                0x0 - <unknown>
```

**Comment by jyn514** [comment]
This is left over from https://github.com/jyn514/rcc/commit/00c2f53b4a6d149847cbb99ed0d614275144ae42 when `as_ir_type` no longer returns an error. The parser needs to desugar this into assigning each member of `s` to the corresponding member of `ss`.
