### ISSUE TITLE
Crash when including signal.h

### ISSUE THREAD

**Issue by jyn514** [jyn514/rcc#76]
```
$ cpp -P -undef <<< '#include<signal.h>' | cargo run
thread 'main' panicked at 'attempt to subtract with overflow', src/backend/mod.rs:146:25
```

Something to do with alignment calculation for structs.

**Comment by jyn514** [comment]
Possibly related:

```c
struct s { int a[24]; } my_s;
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(128)`,
 right: `Some(96)`', /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/faerie-0.11.0/src/artifact/decl.rs:453:5
```

**Comment by jyn514** [comment]
Related: https://github.com/m4b/faerie/issues/95

Somewhere I'm passing size when I should be passing the alignment

**Comment by jyn514** [comment]
Reproduction:

```c
typedef unsigned int __uint32_t;
struct _xmmreg {
  __uint32_t element[4];
};
struct _fpstate {
  __uint32_t _fxsr_env[6];
  struct _xmmreg _xmm[8];
};
thread 'main' panicked at 'attempt to subtract with overflow', src/backend/mod.rs:144:25
```
